# version: '2'

# services:
#   app:
#     build: .
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#   db:
#     image: mongo
#     ports:
#       - "27017:27017"

version: '2'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend: